### ISSUE TITLE
list_row does not work with activeadmin 1.0.0.pre

### ISSUE THREAD

**Issue by cpfarher** [platanus/activeadmin_addons#27]
undefined method `list_row' for  <div class="index_as_table"></div>
:ActiveAdmin::Views::IndexAsTable

**Comment by emilioeduardob** [comment]
Hey @cpfarher , I think what you want is to display rows as in an index as lists. 
`list_row` is only available for `show` views, for the index, you should use `list_column`

**Comment by cpfarher** [comment]
You are right! Sorry....
